// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	ragù          v0.2.3
// source: pkg/api/announce.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Announcement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname                  *UnameInfo       `protobuf:"bytes,1,opt,name=Uname,proto3" json:"Uname,omitempty"`
	Network                *NetworkInfo     `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	PreferredHostPublicKey []byte           `protobuf:"bytes,3,opt,name=PreferredHostPublicKey,proto3" json:"PreferredHostPublicKey,omitempty"`
	AuthorizedKeys         []*AuthorizedKey `protobuf:"bytes,4,rep,name=AuthorizedKeys,proto3" json:"AuthorizedKeys,omitempty"`
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{0}
}

func (x *Announcement) GetUname() *UnameInfo {
	if x != nil {
		return x.Uname
	}
	return nil
}

func (x *Announcement) GetNetwork() *NetworkInfo {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Announcement) GetPreferredHostPublicKey() []byte {
	if x != nil {
		return x.PreferredHostPublicKey
	}
	return nil
}

func (x *Announcement) GetAuthorizedKeys() []*AuthorizedKey {
	if x != nil {
		return x.AuthorizedKeys
	}
	return nil
}

type UnameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelName    string `protobuf:"bytes,1,opt,name=KernelName,proto3" json:"KernelName,omitempty"`
	Hostname      string `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	KernelRelease string `protobuf:"bytes,3,opt,name=KernelRelease,proto3" json:"KernelRelease,omitempty"`
	KernelVersion string `protobuf:"bytes,4,opt,name=KernelVersion,proto3" json:"KernelVersion,omitempty"`
	Machine       string `protobuf:"bytes,5,opt,name=Machine,proto3" json:"Machine,omitempty"`
}

func (x *UnameInfo) Reset() {
	*x = UnameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnameInfo) ProtoMessage() {}

func (x *UnameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnameInfo.ProtoReflect.Descriptor instead.
func (*UnameInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{1}
}

func (x *UnameInfo) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *UnameInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UnameInfo) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *UnameInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *UnameInfo) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

type NetworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkInterfaces []*NetworkInterface `protobuf:"bytes,1,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkInfo) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device    string  `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	Up        bool    `protobuf:"varint,2,opt,name=Up,proto3" json:"Up,omitempty"`
	Addresses []*Addr `protobuf:"bytes,3,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkInterface) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NetworkInterface) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *NetworkInterface) GetAddresses() []*Addr {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidr    string `protobuf:"bytes,1,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Mask    string `protobuf:"bytes,3,opt,name=Mask,proto3" json:"Mask,omitempty"`
}

func (x *Addr) Reset() {
	*x = Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addr) ProtoMessage() {}

func (x *Addr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addr.ProtoReflect.Descriptor instead.
func (*Addr) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{4}
}

func (x *Addr) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Addr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Addr) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type AuthorizedKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User        string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Type        string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Fingerprint string   `protobuf:"bytes,3,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Comment     string   `protobuf:"bytes,5,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Options     []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *AuthorizedKey) Reset() {
	*x = AuthorizedKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_announce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedKey) ProtoMessage() {}

func (x *AuthorizedKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_announce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedKey.ProtoReflect.Descriptor instead.
func (*AuthorizedKey) Descriptor() ([]byte, []int) {
	return file_pkg_api_announce_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizedKey) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthorizedKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthorizedKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AuthorizedKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AuthorizedKey) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_pkg_api_announce_proto protoreflect.FileDescriptor

var file_pkg_api_announce_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x55,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x00, 0x12, 0x23, 0x0a, 0x07,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x00, 0x12, 0x20, 0x0a, 0x16, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x48, 0x6f,
	0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x00, 0x12, 0x2c, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x42,
	0x00, 0x3a, 0x00, 0x22, 0x7c, 0x0a, 0x09, 0x55, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x0a, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x12, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x17, 0x0a, 0x0d, 0x4b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x00, 0x12, 0x17, 0x0a, 0x0d, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x11, 0x0a, 0x07,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a,
	0x00, 0x22, 0x43, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x32, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x54, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x06, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0c, 0x0a, 0x02,
	0x55, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x00, 0x12, 0x1e, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x3b, 0x0a, 0x04,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x04, 0x43, 0x69, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0e, 0x0a, 0x04, 0x4d, 0x61, 0x73, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x6e, 0x0a, 0x0d, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0e, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x15, 0x0a, 0x0b, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x00, 0x12, 0x11, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2d, 0x69, 0x6e, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_announce_proto_rawDescOnce sync.Once
	file_pkg_api_announce_proto_rawDescData = file_pkg_api_announce_proto_rawDesc
)

func file_pkg_api_announce_proto_rawDescGZIP() []byte {
	file_pkg_api_announce_proto_rawDescOnce.Do(func() {
		file_pkg_api_announce_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_announce_proto_rawDescData)
	})
	return file_pkg_api_announce_proto_rawDescData
}

var file_pkg_api_announce_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_announce_proto_goTypes = []interface{}{
	(*Announcement)(nil),     // 0: api.Announcement
	(*UnameInfo)(nil),        // 1: api.UnameInfo
	(*NetworkInfo)(nil),      // 2: api.NetworkInfo
	(*NetworkInterface)(nil), // 3: api.NetworkInterface
	(*Addr)(nil),             // 4: api.Addr
	(*AuthorizedKey)(nil),    // 5: api.AuthorizedKey
}
var file_pkg_api_announce_proto_depIdxs = []int32{
	1, // 0: api.Announcement.Uname:type_name -> api.UnameInfo
	2, // 1: api.Announcement.Network:type_name -> api.NetworkInfo
	5, // 2: api.Announcement.AuthorizedKeys:type_name -> api.AuthorizedKey
	3, // 3: api.NetworkInfo.NetworkInterfaces:type_name -> api.NetworkInterface
	4, // 4: api.NetworkInterface.Addresses:type_name -> api.Addr
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_announce_proto_init() }
func file_pkg_api_announce_proto_init() {
	if File_pkg_api_announce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_announce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Announcement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_announce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_announce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_announce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_announce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_announce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizedKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_announce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_announce_proto_goTypes,
		DependencyIndexes: file_pkg_api_announce_proto_depIdxs,
		MessageInfos:      file_pkg_api_announce_proto_msgTypes,
	}.Build()
	File_pkg_api_announce_proto = out.File
	file_pkg_api_announce_proto_rawDesc = nil
	file_pkg_api_announce_proto_goTypes = nil
	file_pkg_api_announce_proto_depIdxs = nil
}
