// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - ragù               v0.1.0
// source: pkg/api/postlet_api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostletAPIClient is the client API for PostletAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostletAPIClient interface {
	Announce(ctx context.Context, in *Announcement, opts ...grpc.CallOption) (*AnnouncementResponse, error)
}

type postletAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPostletAPIClient(cc grpc.ClientConnInterface) PostletAPIClient {
	return &postletAPIClient{cc}
}

func (c *postletAPIClient) Announce(ctx context.Context, in *Announcement, opts ...grpc.CallOption) (*AnnouncementResponse, error) {
	out := new(AnnouncementResponse)
	err := c.cc.Invoke(ctx, "/api.PostletAPI/Announce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostletAPIServer is the server API for PostletAPI service.
// All implementations must embed UnimplementedPostletAPIServer
// for forward compatibility
type PostletAPIServer interface {
	Announce(context.Context, *Announcement) (*AnnouncementResponse, error)
	mustEmbedUnimplementedPostletAPIServer()
}

// UnimplementedPostletAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPostletAPIServer struct {
}

func (UnimplementedPostletAPIServer) Announce(context.Context, *Announcement) (*AnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedPostletAPIServer) mustEmbedUnimplementedPostletAPIServer() {}

// UnsafePostletAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostletAPIServer will
// result in compilation errors.
type UnsafePostletAPIServer interface {
	mustEmbedUnimplementedPostletAPIServer()
}

func RegisterPostletAPIServer(s grpc.ServiceRegistrar, srv PostletAPIServer) {
	s.RegisterService(&PostletAPI_ServiceDesc, srv)
}

func _PostletAPI_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Announcement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostletAPIServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PostletAPI/Announce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostletAPIServer).Announce(ctx, req.(*Announcement))
	}
	return interceptor(ctx, in, info, handler)
}

// PostletAPI_ServiceDesc is the grpc.ServiceDesc for PostletAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostletAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.PostletAPI",
	HandlerType: (*PostletAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Announce",
			Handler:    _PostletAPI_Announce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/postlet_api.proto",
}

// InstructionClient is the client API for Instruction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstructionClient interface {
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	Script(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error)
	Dismiss(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type instructionClient struct {
	cc grpc.ClientConnInterface
}

func NewInstructionClient(cc grpc.ClientConnInterface) InstructionClient {
	return &instructionClient{cc}
}

func (c *instructionClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/api.Instruction/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instructionClient) Script(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error) {
	out := new(ScriptResponse)
	err := c.cc.Invoke(ctx, "/api.Instruction/Script", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instructionClient) Dismiss(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.Instruction/Dismiss", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstructionServer is the server API for Instruction service.
// All implementations must embed UnimplementedInstructionServer
// for forward compatibility
type InstructionServer interface {
	Command(context.Context, *CommandRequest) (*CommandResponse, error)
	Script(context.Context, *ScriptRequest) (*ScriptResponse, error)
	Dismiss(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedInstructionServer()
}

// UnimplementedInstructionServer must be embedded to have forward compatible implementations.
type UnimplementedInstructionServer struct {
}

func (UnimplementedInstructionServer) Command(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedInstructionServer) Script(context.Context, *ScriptRequest) (*ScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Script not implemented")
}
func (UnimplementedInstructionServer) Dismiss(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dismiss not implemented")
}
func (UnimplementedInstructionServer) mustEmbedUnimplementedInstructionServer() {}

// UnsafeInstructionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstructionServer will
// result in compilation errors.
type UnsafeInstructionServer interface {
	mustEmbedUnimplementedInstructionServer()
}

func RegisterInstructionServer(s grpc.ServiceRegistrar, srv InstructionServer) {
	s.RegisterService(&Instruction_ServiceDesc, srv)
}

func _Instruction_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstructionServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instruction/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstructionServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instruction_Script_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstructionServer).Script(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instruction/Script",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstructionServer).Script(ctx, req.(*ScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instruction_Dismiss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstructionServer).Dismiss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Instruction/Dismiss",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstructionServer).Dismiss(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Instruction_ServiceDesc is the grpc.ServiceDesc for Instruction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Instruction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Instruction",
	HandlerType: (*InstructionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Instruction_Command_Handler,
		},
		{
			MethodName: "Script",
			Handler:    _Instruction_Script_Handler,
		},
		{
			MethodName: "Dismiss",
			Handler:    _Instruction_Dismiss_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/postlet_api.proto",
}
