// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	ragù          v0.1.0
// source: pkg/api/relay.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_Success Result = 0
	Result_Error   Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "Success",
		1: "Error",
	}
	Result_value = map[string]int32{
		"Success": 0,
		"Error":   1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_relay_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_pkg_api_relay_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_And Operator = 0
	Operator_Or  Operator = 1
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "And",
		1: "Or",
	}
	Operator_value = map[string]int32{
		"And": 0,
		"Or":  1,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_relay_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_pkg_api_relay_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{1}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept  bool   `protobuf:"varint,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Instruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Instruction:
	//	*Instruction_Dismiss
	//	*Instruction_Command
	//	*Instruction_Script
	Instruction isInstruction_Instruction `protobuf_oneof:"Instruction"`
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{1}
}

func (m *Instruction) GetInstruction() isInstruction_Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (x *Instruction) GetDismiss() *Dismiss {
	if x, ok := x.GetInstruction().(*Instruction_Dismiss); ok {
		return x.Dismiss
	}
	return nil
}

func (x *Instruction) GetCommand() *Command {
	if x, ok := x.GetInstruction().(*Instruction_Command); ok {
		return x.Command
	}
	return nil
}

func (x *Instruction) GetScript() *Script {
	if x, ok := x.GetInstruction().(*Instruction_Script); ok {
		return x.Script
	}
	return nil
}

type isInstruction_Instruction interface {
	isInstruction_Instruction()
}

type Instruction_Dismiss struct {
	Dismiss *Dismiss `protobuf:"bytes,1,opt,name=Dismiss,proto3,oneof"`
}

type Instruction_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=Command,proto3,oneof"`
}

type Instruction_Script struct {
	Script *Script `protobuf:"bytes,3,opt,name=Script,proto3,oneof"`
}

func (*Instruction_Dismiss) isInstruction_Instruction() {}

func (*Instruction_Command) isInstruction_Instruction() {}

func (*Instruction_Script) isInstruction_Instruction() {}

type InstructionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint string       `protobuf:"bytes,1,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Instruction *Instruction `protobuf:"bytes,2,opt,name=Instruction,proto3" json:"Instruction,omitempty"`
}

func (x *InstructionRequest) Reset() {
	*x = InstructionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstructionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionRequest) ProtoMessage() {}

func (x *InstructionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionRequest.ProtoReflect.Descriptor instead.
func (*InstructionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{2}
}

func (x *InstructionRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *InstructionRequest) GetInstruction() *Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

type InstructionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint string `protobuf:"bytes,1,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Result      Result `protobuf:"varint,2,opt,name=Result,proto3,enum=api.Result" json:"Result,omitempty"`
	Error       string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	// Types that are assignable to Instruction:
	//	*InstructionResponse_CommandOutput
	//	*InstructionResponse_ScriptOutput
	Instruction isInstructionResponse_Instruction `protobuf_oneof:"instruction"`
}

func (x *InstructionResponse) Reset() {
	*x = InstructionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionResponse) ProtoMessage() {}

func (x *InstructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionResponse.ProtoReflect.Descriptor instead.
func (*InstructionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{3}
}

func (x *InstructionResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *InstructionResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_Success
}

func (x *InstructionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (m *InstructionResponse) GetInstruction() isInstructionResponse_Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (x *InstructionResponse) GetCommandOutput() *CommandOutput {
	if x, ok := x.GetInstruction().(*InstructionResponse_CommandOutput); ok {
		return x.CommandOutput
	}
	return nil
}

func (x *InstructionResponse) GetScriptOutput() *ScriptOutput {
	if x, ok := x.GetInstruction().(*InstructionResponse_ScriptOutput); ok {
		return x.ScriptOutput
	}
	return nil
}

type isInstructionResponse_Instruction interface {
	isInstructionResponse_Instruction()
}

type InstructionResponse_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,4,opt,name=CommandOutput,proto3,oneof"`
}

type InstructionResponse_ScriptOutput struct {
	ScriptOutput *ScriptOutput `protobuf:"bytes,5,opt,name=ScriptOutput,proto3,oneof"`
}

func (*InstructionResponse_CommandOutput) isInstructionResponse_Instruction() {}

func (*InstructionResponse_ScriptOutput) isInstructionResponse_Instruction() {}

type Dismiss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Dismiss) Reset() {
	*x = Dismiss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dismiss) ProtoMessage() {}

func (x *Dismiss) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dismiss.ProtoReflect.Descriptor instead.
func (*Dismiss) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{4}
}

type NotifyMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator         Operator `protobuf:"varint,1,opt,name=Operator,proto3,enum=api.Operator" json:"Operator,omitempty"`
	HasAuthorizedKey string   `protobuf:"bytes,2,opt,name=HasAuthorizedKey,proto3" json:"HasAuthorizedKey,omitempty"`
	HasIPAddress     string   `protobuf:"bytes,3,opt,name=HasIPAddress,proto3" json:"HasIPAddress,omitempty"`
	HasHostname      string   `protobuf:"bytes,4,opt,name=HasHostname,proto3" json:"HasHostname,omitempty"`
}

func (x *NotifyMatch) Reset() {
	*x = NotifyMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMatch) ProtoMessage() {}

func (x *NotifyMatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMatch.ProtoReflect.Descriptor instead.
func (*NotifyMatch) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyMatch) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_And
}

func (x *NotifyMatch) GetHasAuthorizedKey() string {
	if x != nil {
		return x.HasAuthorizedKey
	}
	return ""
}

func (x *NotifyMatch) GetHasIPAddress() string {
	if x != nil {
		return x.HasIPAddress
	}
	return ""
}

func (x *NotifyMatch) GetHasHostname() string {
	if x != nil {
		return x.HasHostname
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint  string        `protobuf:"bytes,1,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Announcement *Announcement `protobuf:"bytes,2,opt,name=Announcement,proto3" json:"Announcement,omitempty"`
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *NotifyResponse) GetAnnouncement() *Announcement {
	if x != nil {
		return x.Announcement
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string   `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	Env     []string `protobuf:"bytes,3,rep,name=Env,proto3" json:"Env,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Script struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interpreter string   `protobuf:"bytes,1,opt,name=Interpreter,proto3" json:"Interpreter,omitempty"`
	Script      string   `protobuf:"bytes,2,opt,name=Script,proto3" json:"Script,omitempty"`
	Args        []string `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`
}

func (x *Script) Reset() {
	*x = Script{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{8}
}

func (x *Script) GetInterpreter() string {
	if x != nil {
		return x.Interpreter
	}
	return ""
}

func (x *Script) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Script) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32  `protobuf:"varint,2,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Stdout   string `protobuf:"bytes,3,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr   string `protobuf:"bytes,4,opt,name=Stderr,proto3" json:"Stderr,omitempty"`
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{9}
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandOutput) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type ScriptOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32  `protobuf:"varint,1,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Stdout   string `protobuf:"bytes,2,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr   string `protobuf:"bytes,3,opt,name=Stderr,proto3" json:"Stderr,omitempty"`
}

func (x *ScriptOutput) Reset() {
	*x = ScriptOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptOutput) ProtoMessage() {}

func (x *ScriptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptOutput.ProtoReflect.Descriptor instead.
func (*ScriptOutput) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{10}
}

func (x *ScriptOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ScriptOutput) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ScriptOutput) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type Announcement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname                  *UnameInfo       `protobuf:"bytes,1,opt,name=Uname,proto3" json:"Uname,omitempty"`
	Network                *NetworkInfo     `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	PreferredHostPublicKey []byte           `protobuf:"bytes,3,opt,name=PreferredHostPublicKey,proto3" json:"PreferredHostPublicKey,omitempty"`
	AuthorizedKeys         []*AuthorizedKey `protobuf:"bytes,4,rep,name=AuthorizedKeys,proto3" json:"AuthorizedKeys,omitempty"`
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{11}
}

func (x *Announcement) GetUname() *UnameInfo {
	if x != nil {
		return x.Uname
	}
	return nil
}

func (x *Announcement) GetNetwork() *NetworkInfo {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Announcement) GetPreferredHostPublicKey() []byte {
	if x != nil {
		return x.PreferredHostPublicKey
	}
	return nil
}

func (x *Announcement) GetAuthorizedKeys() []*AuthorizedKey {
	if x != nil {
		return x.AuthorizedKeys
	}
	return nil
}

type UnameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelName    string `protobuf:"bytes,1,opt,name=KernelName,proto3" json:"KernelName,omitempty"`
	Hostname      string `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	KernelRelease string `protobuf:"bytes,3,opt,name=KernelRelease,proto3" json:"KernelRelease,omitempty"`
	KernelVersion string `protobuf:"bytes,4,opt,name=KernelVersion,proto3" json:"KernelVersion,omitempty"`
	Machine       string `protobuf:"bytes,5,opt,name=Machine,proto3" json:"Machine,omitempty"`
}

func (x *UnameInfo) Reset() {
	*x = UnameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnameInfo) ProtoMessage() {}

func (x *UnameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnameInfo.ProtoReflect.Descriptor instead.
func (*UnameInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{12}
}

func (x *UnameInfo) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *UnameInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UnameInfo) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *UnameInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *UnameInfo) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

type NetworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkInterfaces []*NetworkInterface `protobuf:"bytes,1,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkInfo) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device    string  `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	Up        bool    `protobuf:"varint,2,opt,name=Up,proto3" json:"Up,omitempty"`
	Addresses []*Addr `protobuf:"bytes,3,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkInterface) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NetworkInterface) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *NetworkInterface) GetAddresses() []*Addr {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidr    string `protobuf:"bytes,1,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Mask    string `protobuf:"bytes,3,opt,name=Mask,proto3" json:"Mask,omitempty"`
}

func (x *Addr) Reset() {
	*x = Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addr) ProtoMessage() {}

func (x *Addr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addr.ProtoReflect.Descriptor instead.
func (*Addr) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{15}
}

func (x *Addr) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Addr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Addr) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type AuthorizedKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User        string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Type        string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Fingerprint string   `protobuf:"bytes,3,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Comment     string   `protobuf:"bytes,5,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Options     []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *AuthorizedKey) Reset() {
	*x = AuthorizedKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedKey) ProtoMessage() {}

func (x *AuthorizedKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedKey.ProtoReflect.Descriptor instead.
func (*AuthorizedKey) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{16}
}

func (x *AuthorizedKey) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthorizedKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthorizedKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AuthorizedKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AuthorizedKey) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ClientConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*ClientConnectRequest_ConnectionRequest
	//	*ClientConnectRequest_KexResponse
	Request isClientConnectRequest_Request `protobuf_oneof:"Request"`
}

func (x *ClientConnectRequest) Reset() {
	*x = ClientConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectRequest) ProtoMessage() {}

func (x *ClientConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectRequest.ProtoReflect.Descriptor instead.
func (*ClientConnectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{17}
}

func (m *ClientConnectRequest) GetRequest() isClientConnectRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientConnectRequest) GetConnectionRequest() *ConnectionRequest {
	if x, ok := x.GetRequest().(*ClientConnectRequest_ConnectionRequest); ok {
		return x.ConnectionRequest
	}
	return nil
}

func (x *ClientConnectRequest) GetKexResponse() *KexResponse {
	if x, ok := x.GetRequest().(*ClientConnectRequest_KexResponse); ok {
		return x.KexResponse
	}
	return nil
}

type isClientConnectRequest_Request interface {
	isClientConnectRequest_Request()
}

type ClientConnectRequest_ConnectionRequest struct {
	ConnectionRequest *ConnectionRequest `protobuf:"bytes,1,opt,name=ConnectionRequest,proto3,oneof"`
}

type ClientConnectRequest_KexResponse struct {
	KexResponse *KexResponse `protobuf:"bytes,2,opt,name=KexResponse,proto3,oneof"`
}

func (*ClientConnectRequest_ConnectionRequest) isClientConnectRequest_Request() {}

func (*ClientConnectRequest_KexResponse) isClientConnectRequest_Request() {}

type ClientConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*ClientConnectResponse_ConnectionResponse
	//	*ClientConnectResponse_KexRequest
	Response isClientConnectResponse_Response `protobuf_oneof:"Response"`
}

func (x *ClientConnectResponse) Reset() {
	*x = ClientConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectResponse) ProtoMessage() {}

func (x *ClientConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectResponse.ProtoReflect.Descriptor instead.
func (*ClientConnectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{18}
}

func (m *ClientConnectResponse) GetResponse() isClientConnectResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ClientConnectResponse) GetConnectionResponse() *ConnectionResponse {
	if x, ok := x.GetResponse().(*ClientConnectResponse_ConnectionResponse); ok {
		return x.ConnectionResponse
	}
	return nil
}

func (x *ClientConnectResponse) GetKexRequest() *KexRequest {
	if x, ok := x.GetResponse().(*ClientConnectResponse_KexRequest); ok {
		return x.KexRequest
	}
	return nil
}

type isClientConnectResponse_Response interface {
	isClientConnectResponse_Response()
}

type ClientConnectResponse_ConnectionResponse struct {
	ConnectionResponse *ConnectionResponse `protobuf:"bytes,1,opt,name=ConnectionResponse,proto3,oneof"`
}

type ClientConnectResponse_KexRequest struct {
	KexRequest *KexRequest `protobuf:"bytes,2,opt,name=KexRequest,proto3,oneof"`
}

func (*ClientConnectResponse_ConnectionResponse) isClientConnectResponse_Response() {}

func (*ClientConnectResponse_KexRequest) isClientConnectResponse_Response() {}

type ConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicClientKey []byte `protobuf:"bytes,1,opt,name=PublicClientKey,proto3" json:"PublicClientKey,omitempty"`
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{19}
}

func (x *ConnectionRequest) GetPublicClientKey() []byte {
	if x != nil {
		return x.PublicClientKey
	}
	return nil
}

type ConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept bool `protobuf:"varint,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{20}
}

func (x *ConnectionResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type KexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce                    []byte `protobuf:"bytes,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	PublicHostKey            []byte `protobuf:"bytes,2,opt,name=PublicHostKey,proto3" json:"PublicHostKey,omitempty"`
	ServerEphemeralPublicKey []byte `protobuf:"bytes,3,opt,name=ServerEphemeralPublicKey,proto3" json:"ServerEphemeralPublicKey,omitempty"`
}

func (x *KexRequest) Reset() {
	*x = KexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KexRequest) ProtoMessage() {}

func (x *KexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KexRequest.ProtoReflect.Descriptor instead.
func (*KexRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{21}
}

func (x *KexRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *KexRequest) GetPublicHostKey() []byte {
	if x != nil {
		return x.PublicHostKey
	}
	return nil
}

func (x *KexRequest) GetServerEphemeralPublicKey() []byte {
	if x != nil {
		return x.ServerEphemeralPublicKey
	}
	return nil
}

type KexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientEphemeralPublicKey []byte `protobuf:"bytes,1,opt,name=ClientEphemeralPublicKey,proto3" json:"ClientEphemeralPublicKey,omitempty"`
	Signature                []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *KexResponse) Reset() {
	*x = KexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_relay_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KexResponse) ProtoMessage() {}

func (x *KexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_relay_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KexResponse.ProtoReflect.Descriptor instead.
func (*KexResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_relay_proto_rawDescGZIP(), []int{22}
}

func (x *KexResponse) GetClientEphemeralPublicKey() []byte {
	if x != nil {
		return x.ClientEphemeralPublicKey
	}
	return nil
}

func (x *KexResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pkg_api_relay_proto protoreflect.FileDescriptor

var file_pkg_api_relay_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x31, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x87, 0x01,
	0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x07, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x42, 0x00, 0x48, 0x00,
	0x12, 0x21, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42,
	0x00, 0x48, 0x00, 0x12, 0x1f, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x42, 0x00, 0x48, 0x00, 0x3a, 0x00, 0x42, 0x0f, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x00, 0x22, 0x56, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x0b, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x00, 0x12, 0x27, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x00, 0x3a, 0x00, 0x22,
	0xcb, 0x01, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x1d,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x00, 0x12, 0x0f, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x2d,
	0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x00, 0x48, 0x00, 0x12, 0x2b, 0x0a,
	0x0c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x00, 0x48, 0x00, 0x3a, 0x00, 0x42, 0x0f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x00, 0x22, 0x0b, 0x0a,
	0x07, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x3a, 0x00, 0x22, 0x7d, 0x0a, 0x0b, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x08, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x00, 0x12, 0x1a, 0x0a, 0x10,
	0x48, 0x61, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x16, 0x0a, 0x0c, 0x48, 0x61, 0x73, 0x49,
	0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00,
	0x12, 0x15, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x54, 0x0a, 0x0e, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x0b, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x00, 0x12, 0x29, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x00, 0x3a, 0x00, 0x22,
	0x3d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x11, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0e, 0x0a,
	0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0d, 0x0a,
	0x03, 0x45, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x43,
	0x0a, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x15, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12,
	0x10, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x00, 0x12, 0x0e, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x42,
	0x00, 0x3a, 0x00, 0x22, 0x49, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x53, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x48,
	0x0a, 0x0c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12,
	0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x55, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x00, 0x12, 0x23, 0x0a, 0x07, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x00, 0x12,
	0x20, 0x0a, 0x16, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42,
	0x00, 0x12, 0x2c, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x42, 0x00, 0x3a,
	0x00, 0x22, 0x7c, 0x0a, 0x09, 0x55, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x0a, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x00, 0x12, 0x12, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x17, 0x0a, 0x0d, 0x4b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x00, 0x12, 0x17, 0x0a, 0x0d, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22,
	0x43, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32,
	0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x42, 0x00, 0x3a, 0x00, 0x22, 0x54, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0c, 0x0a, 0x02, 0x55, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x00, 0x12, 0x1e, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x3b, 0x0a, 0x04, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x0e, 0x0a, 0x04, 0x43, 0x69, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0e, 0x0a, 0x04, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x6e, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x0e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x15, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12,
	0x11, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x00, 0x12, 0x11, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x87, 0x01, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x00, 0x48, 0x00, 0x12, 0x29, 0x0a, 0x0b, 0x4b, 0x65, 0x78, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4b, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x00,
	0x48, 0x00, 0x3a, 0x00, 0x42, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x00, 0x22, 0x89, 0x01, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x00, 0x48, 0x00, 0x12, 0x27, 0x0a, 0x0a, 0x4b, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4b,
	0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x00, 0x48, 0x00, 0x3a, 0x00, 0x42,
	0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x00, 0x22, 0x30, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x3a, 0x00, 0x22,
	0x28, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x5c, 0x0a, 0x0a, 0x4b, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x12, 0x17, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42,
	0x00, 0x12, 0x22, 0x0a, 0x18, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x70, 0x68, 0x65, 0x6d,
	0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x48, 0x0a, 0x0b, 0x4b, 0x65, 0x78, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x12, 0x13, 0x0a, 0x09, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x3a,
	0x00, 0x2a, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x10, 0x01, 0x1a, 0x00, 0x2a, 0x1d, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x72,
	0x10, 0x01, 0x1a, 0x00, 0x32, 0xcf, 0x02, 0x0a, 0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x32,
	0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x12, 0x46, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x00, 0x30, 0x01, 0x12,
	0x43, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x1a, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x6f,
	0x73, 0x74, 0x2d, 0x69, 0x6e, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_relay_proto_rawDescOnce sync.Once
	file_pkg_api_relay_proto_rawDescData = file_pkg_api_relay_proto_rawDesc
)

func file_pkg_api_relay_proto_rawDescGZIP() []byte {
	file_pkg_api_relay_proto_rawDescOnce.Do(func() {
		file_pkg_api_relay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_relay_proto_rawDescData)
	})
	return file_pkg_api_relay_proto_rawDescData
}

var file_pkg_api_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_api_relay_proto_goTypes = []interface{}{
	(Result)(0),                   // 0: api.Result
	(Operator)(0),                 // 1: api.Operator
	(*Response)(nil),              // 2: api.Response
	(*Instruction)(nil),           // 3: api.Instruction
	(*InstructionRequest)(nil),    // 4: api.InstructionRequest
	(*InstructionResponse)(nil),   // 5: api.InstructionResponse
	(*Dismiss)(nil),               // 6: api.Dismiss
	(*NotifyMatch)(nil),           // 7: api.NotifyMatch
	(*NotifyResponse)(nil),        // 8: api.NotifyResponse
	(*Command)(nil),               // 9: api.Command
	(*Script)(nil),                // 10: api.Script
	(*CommandOutput)(nil),         // 11: api.CommandOutput
	(*ScriptOutput)(nil),          // 12: api.ScriptOutput
	(*Announcement)(nil),          // 13: api.Announcement
	(*UnameInfo)(nil),             // 14: api.UnameInfo
	(*NetworkInfo)(nil),           // 15: api.NetworkInfo
	(*NetworkInterface)(nil),      // 16: api.NetworkInterface
	(*Addr)(nil),                  // 17: api.Addr
	(*AuthorizedKey)(nil),         // 18: api.AuthorizedKey
	(*ClientConnectRequest)(nil),  // 19: api.ClientConnectRequest
	(*ClientConnectResponse)(nil), // 20: api.ClientConnectResponse
	(*ConnectionRequest)(nil),     // 21: api.ConnectionRequest
	(*ConnectionResponse)(nil),    // 22: api.ConnectionResponse
	(*KexRequest)(nil),            // 23: api.KexRequest
	(*KexResponse)(nil),           // 24: api.KexResponse
}
var file_pkg_api_relay_proto_depIdxs = []int32{
	6,  // 0: api.Instruction.Dismiss:type_name -> api.Dismiss
	9,  // 1: api.Instruction.Command:type_name -> api.Command
	10, // 2: api.Instruction.Script:type_name -> api.Script
	3,  // 3: api.InstructionRequest.Instruction:type_name -> api.Instruction
	0,  // 4: api.InstructionResponse.Result:type_name -> api.Result
	11, // 5: api.InstructionResponse.CommandOutput:type_name -> api.CommandOutput
	12, // 6: api.InstructionResponse.ScriptOutput:type_name -> api.ScriptOutput
	1,  // 7: api.NotifyMatch.Operator:type_name -> api.Operator
	13, // 8: api.NotifyResponse.Announcement:type_name -> api.Announcement
	14, // 9: api.Announcement.Uname:type_name -> api.UnameInfo
	15, // 10: api.Announcement.Network:type_name -> api.NetworkInfo
	18, // 11: api.Announcement.AuthorizedKeys:type_name -> api.AuthorizedKey
	16, // 12: api.NetworkInfo.NetworkInterfaces:type_name -> api.NetworkInterface
	17, // 13: api.NetworkInterface.Addresses:type_name -> api.Addr
	21, // 14: api.ClientConnectRequest.ConnectionRequest:type_name -> api.ConnectionRequest
	24, // 15: api.ClientConnectRequest.KexResponse:type_name -> api.KexResponse
	22, // 16: api.ClientConnectResponse.ConnectionResponse:type_name -> api.ConnectionResponse
	23, // 17: api.ClientConnectResponse.KexRequest:type_name -> api.KexRequest
	13, // 18: api.Relay.Announce:input_type -> api.Announcement
	5,  // 19: api.Relay.StreamInstructions:input_type -> api.InstructionResponse
	19, // 20: api.Relay.ClientConnect:input_type -> api.ClientConnectRequest
	7,  // 21: api.Relay.Notify:input_type -> api.NotifyMatch
	3,  // 22: api.Relay.SendInstruction:input_type -> api.Instruction
	2,  // 23: api.Relay.Announce:output_type -> api.Response
	3,  // 24: api.Relay.StreamInstructions:output_type -> api.Instruction
	20, // 25: api.Relay.ClientConnect:output_type -> api.ClientConnectResponse
	8,  // 26: api.Relay.Notify:output_type -> api.NotifyResponse
	5,  // 27: api.Relay.SendInstruction:output_type -> api.InstructionResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_api_relay_proto_init() }
func file_pkg_api_relay_proto_init() {
	if File_pkg_api_relay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_relay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstructionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstructionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dismiss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Script); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Announcement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizedKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_relay_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_api_relay_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Instruction_Dismiss)(nil),
		(*Instruction_Command)(nil),
		(*Instruction_Script)(nil),
	}
	file_pkg_api_relay_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*InstructionResponse_CommandOutput)(nil),
		(*InstructionResponse_ScriptOutput)(nil),
	}
	file_pkg_api_relay_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*ClientConnectRequest_ConnectionRequest)(nil),
		(*ClientConnectRequest_KexResponse)(nil),
	}
	file_pkg_api_relay_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*ClientConnectResponse_ConnectionResponse)(nil),
		(*ClientConnectResponse_KexRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_relay_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_relay_proto_goTypes,
		DependencyIndexes: file_pkg_api_relay_proto_depIdxs,
		EnumInfos:         file_pkg_api_relay_proto_enumTypes,
		MessageInfos:      file_pkg_api_relay_proto_msgTypes,
	}.Build()
	File_pkg_api_relay_proto = out.File
	file_pkg_api_relay_proto_rawDesc = nil
	file_pkg_api_relay_proto_goTypes = nil
	file_pkg_api_relay_proto_depIdxs = nil
}
